### PR TITLE
 Remove unneeded concurrency things

### PR DESCRIPTION
**Pull request by taer**
The mutex and atomicBolean aren't needed in this context.

The mutex is only contained in a local variable in sequential code. It isn't shared w/ any other threads. The same with the atomic bolean.

Both of these constructs are inside the launched co-routine, and aren't shared outside. Therefore they can't help control any other shared access.

### CODE REVIEW

**Comment by robert-csdisco** [comment]
The gist of this is I'm looking into why we have some nasty corner cases.  This isn't it, but it's a slight optimization that could be made wrt the flow handling

**Comment by taer** [comment]
@lowasser Just checking in to see if this project is still alive or if you have any questions/concerns on this?

**Comment by taer** [comment]
@jamesward Thoughts on this?

**Comment by jamesward** [comment]
We will need @lowasser to review this.

**Comment by taer** [comment]
Ok. The idea here is none of these mutexes or atomicBooleans are ever used concurrently they're very sequential in their nature, so having the lock there doesn't accomplish anything.

**Comment by lowasser** [comment]
This does look safe to me.

**Review by jamesward — APPROVED** [review]

**Pull request merged**
