### PR TITLE
Example merge - fixes #138

### LINKED ISSUE #138: Integrate `examples-android` into `examples`
Followup to #131 and #137.

Suggested `examples` layout:

- `android-client`
- `cli-client`
- `common`
- `server`

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by jamesward** [comment]
This replaces #180 to see if making the PR from a branch in this repo makes the tests not flaky.

**Comment by bshaffer** [comment]
@jamesward one of the checks never finishes (It's been over an hour since it started!)

I saw this happen on a previous build also, any idea what's causing it?

**Comment by jamesward** [comment]
Looks like: `Caused by: java.lang.OutOfMemoryError: Metaspace`
Erggg...  I'll investigate.

**Comment by jamesward** [comment]
Woot! Passing.

**Review by bshaffer — APPROVED** [review]

**Pull request merged**
