### PR TITLE
feat: use jar for protoc

### PR DESCRIPTION
**Pull request by bshaffer**
- addresses #92 
 - This may address #98

### CODE REVIEW

**Comment by jamesward** [comment]
Nice! Did you want to keep the exe's for one release so that we can validate things work with the new approach?  Or just go for it. I'm fine either way.

**Comment by jamesward** [comment]
If you release a `0.2.0-SNAPSHOT` to the Maven Snapshot repo, then I can easily test on Windows.  I'd think there is an easy way to do that with Gradle, but I haven't done it.

**Comment by jamesward** [comment]
I've tested this on Windows & Linux with Gradle & Maven and it works great.

**Review by jamesward — APPROVED** [review]

**Comment by jamesward** [comment]
Let's release a `0.2.0` and then we can update samples & docs.

**Comment by bshaffer** [comment]
Agreed! I will create the release tomorrow!

**Pull request merged**
