### PR TITLE
kotlin protos

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by xmlking** [comment]
How to add an item to repeated field?
getting compilation error with following examples 

```
Cannot access class 'com.google.protobuf.kotlin.DslList'. Check your module classpath for missing or conflicting dependencies
```

```kotlin
val request = linkRequest {
    profile = Profile.PROFILE_RO
    this.person = person
    addresses += address
}
```

```kotlin
val request = linkRequest {
    profile = Profile.PROFILE_RO
    this.person = person
    addresses.add(address)
}
```

**Comment by xmlking** [comment]
Resolved  above issue. 
I had to add ` implementation("com.google.protobuf:protobuf-kotlin:3.17.+")` gradle dependency even though I am not explicitly using any classes in package `com.google.protobuf.kotlin.*`

This is a good point to document 
```
    implementation(libs.protobuf.java)
    implementation(libs.protobuf.kotlin)
```

**Comment by Kernald** [comment]
Am I correct to assume that this doesn't support proto-lite? The gRPC macro takes  in a `flavor` argument that's pretty much just forwarded to the Java gRPC library, and picks the correct dependency depending on the `flavor`. Should a similar thing be done here as well?

**Comment by jamesward** [comment]
Today there isn't much difference with the Kotlin lite protos but you can use them:
https://github.com/grpc/grpc-kotlin/blob/master/examples/stub-lite/build.gradle.kts#L49-L64

The Java protos are pretty different though.  And you do need to set the lite deps when using the lite protos:
https://github.com/grpc/grpc-kotlin/blob/master/examples/stub-lite/build.gradle.kts#L18-L20

**Comment by Kernald** [comment]
The question was about the Bazel integration, sorry I wasn't clear, I didn't look closely at what this PR was adding (just noted it added the Bazel `kt_jvm_proto_library` macro) - specifically, `kt_jvm_proto_library` not having a `flavor` argument. Which ends up generating a library that always depends on the regular Java proto library, with no way to target the lite one.

**Comment by jamesward** [comment]
Ah, yeah I'm not sure on the Bazel side.  Maybe @aragos has some info on that.

**Comment by Kernald** [comment]
I just tried a fairly simple patch locally which seems to be working just fine - I'll send a PR very soon.

**Comment by Kernald** [comment]
PR opened, #350

**Comment by blockjon-dd** [comment]
Hi @jamesward - if I do something like this:
```
bazel build //examples/protos/src/main/proto/io/grpc/examples/helloworld:hello_world_kt_grpc
```
Should the resulting .jar file contain the classes that allow me to actually instantiate an instance of HelloRequest and HelloReply? Or, do I need to rely on the java classes for that?

**Comment by blockjon-dd** [comment]
I'm not seeing the example Request and Response files that I would expect:
```
jon.block@DQK62VCYHR grpc-kotlin % bazel build //examples/protos/src/main/proto/io/grpc/examples/helloworld:hello_world_kt_grpc
Starting local Bazel server and connecting to it...
INFO: Analyzed target //examples/protos/src/main/proto/io/grpc/examples/helloworld:hello_world_kt_grpc (121 packages loaded, 2306 targets configured).
INFO: Found 1 target...
Target //examples/protos/src/main/proto/io/grpc/examples/helloworld:hello_world_kt_grpc up-to-date:
  bazel-bin/examples/protos/src/main/proto/io/grpc/examples/helloworld/hello_world_kt_grpc.jar
  bazel-bin/examples/protos/src/main/proto/io/grpc/examples/helloworld/hello_world_kt_grpc.jdeps
INFO: Elapsed time: 5.585s, Critical Path: 0.41s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
jon.block@DQK62VCYHR grpc-kotlin % unzip -l bazel-bin/examples/protos/src/main/proto/io/grpc/examples/helloworld/hello_world_kt_grpc.jar
Archive:  bazel-bin/examples/protos/src/main/proto/io/grpc/examples/helloworld/hello_world_kt_grpc.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  01-01-2010 00:00   META-INF/
      182  01-01-2010 00:00   META-INF/MANIFEST.MF
       24  01-01-2010 00:00   META-INF/examples_protos_src_main_proto_io_grpc_examples_helloworld-hello_world_kt_grpc.kotlin_module
        0  01-01-2010 00:00   io/
        0  01-01-2010 00:00   io/grpc/
        0  01-01-2010 00:00   io/grpc/examples/
        0  01-01-2010 00:00   io/grpc/examples/helloworld/
     2339  01-01-2010 00:00   io/grpc/examples/helloworld/GreeterGrpcKt$GreeterCoroutineImplBase$bindService$1.class
     4336  01-01-2010 00:00   io/grpc/examples/helloworld/GreeterGrpcKt$GreeterCoroutineImplBase.class
     1988  01-01-2010 00:00   io/grpc/examples/helloworld/GreeterGrpcKt$GreeterCoroutineStub$sayHello$1.class
     5081  01-01-2010 00:00   io/grpc/examples/helloworld/GreeterGrpcKt$GreeterCoroutineStub.class
     2174  01-01-2010 00:00   io/grpc/examples/helloworld/GreeterGrpcKt.class
---------                     -------
    16124                     12 files
    ```

**Pull request merged**
