### PR TITLE
support proto3 optional fields

### PR DESCRIPTION
**Pull request by azulkarnyaev**
Currently, java proto3 compiler supports optional fields. But unfortunately, Kotlin grpc compiler fails to compile such fields. There is a small change based on the [docs](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md). 

As protobuf supports the feature since version 3.13, I updated protobuf and grpc version in the gradle build script.

### CODE REVIEW

**Comment by azulkarnyaev** [comment]
@jamesward, is there any chance that you have time to review the PR?

**Comment by jamesward** [comment]
I'll need @lowasser to handle this since it's beyond my abilities :)

**Comment by azulkarnyaev** [comment]
@lowasser can you review the PR, please?

**Comment by jiraguha** [comment]
Hey since Protobuff v3.15.0 optional is not experimental. Therefore, when can we move on to this issue?

**Comment by RationalityFrontline** [comment]
We have urgent need for optional fields, and it's been 3 months since this pr is created. Please speed up on this process.

**Comment by xmlking** [comment]
we are also blocked waiting for this PR merged. please review and approve ASAP

**Pull request merged**
