### PR TITLE
Recover cancellation when close responses flow

### PR DESCRIPTION
**Pull request by akandratovich**
When streaming call is cancelled it's handled in `sender` coroutine (lines 311-319). Both client call cancellation (line 316) and failure propagation (line 317) eventually reach the listener `onClose` callback (where `responses` flow is closed), but which one reaches the place first is racy. When failure propagation reaches the callback first, the flow is cancelled with cancellation exception (expected). But if the client call cancel reaches the callback first, the flow is cancelled with GRPC status exception (unexpected).

This change recovers the cancellation from GRPC status exception if it was the cause to make the behavior deterministic and aligned with expectations.

I don't know how to test this change reliably. I succeeded to reproduce the issue via slow emulator tests only with some chance over 100+ runs.

### CODE REVIEW

**Comment by akandratovich** [comment]
There is a failing test that asserts that flow fails with grpc error if request flow throws `CancellationException`. Is it part of the contract? The similar java test asserts on `RuntimeException`.

**Comment by jamesward** [comment]
That is a question for @lowasser

**Comment by lowasser** [comment]
It seems reasonable to delete that test, I don't think it should be part of the contract.

**Comment by akandratovich** [comment]
I have "removed" the test.

**Review by lowasser — APPROVED** [review]

**Pull request merged**
