### PR TITLE
Example merge - fixes #138

### LINKED ISSUE #138: Integrate `examples-android` into `examples`
Followup to #131 and #137.

Suggested `examples` layout:

- `android-client`
- `cli-client`
- `common`
- `server`

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Review by bshaffer — COMMENTED** [review]
I tested all of these except for the cloud run button and the android with an actual device / non-local server.

This is fantastic! Amazing work! We just need to get Bazel and gradle tests passing...

**Comment by jamesward** [comment]
I got the Bazel check passing so now it seems we are just blocked on flaky Gradle tests.  Not sure what is up with these since they all regularly pass locally.  The most recent failure was:
```
io.grpc.testing.integration.Http2OkHttpTest > cancelAfterFirstResponse FAILED
    kotlin.KotlinNullPointerException
```

**Comment by jamesward** [comment]
I can't make these tests pass.  Are the interop tests potentially running in parallel across different matrices against a shared resource that might be causing some state to get out-of-whack?

**Comment by bshaffer** [comment]
@jamesward these tests are passing in `master` as of 6 days ago. It could also be because you're submitting from a branch (that thing again)

**Pull request closed without merging**
