### PR TITLE
Use proper Maven targets rather than legacy compat ones

### PR DESCRIPTION
**Pull request by Kernald**
Using legacy targets forces downstream users to enable compat repositories as well.

### CODE REVIEW

**Comment by jamesward** [comment]
The Bazel tests are failing with the same issues I ran into & fixed in #319.  If you rebase this on #319, that'd be awesome.  Otherwise, you can copy & paste / cherry-pick any of my changes.

**Comment by Kernald** [comment]
I was actually about to submit another PR fixing Bazel version to 4.2.2. While updating `grpc-java` is the proper solution, fixing the version we use (for now to 4.2.2, or to 5.0. once #319 is merged) is probably a good thing moving forward anyway :-)

**Comment by Kernald** [comment]
#322 is adding a `.bazelversion`, I'm happy to update it to `5.0.0` and wait for #319 to be merged.

**Review by jamesward — APPROVED** [review]

**Comment by jamesward** [comment]
Thank you!

**Pull request merged**
