### PR TITLE
Make interop_testing a subproject.  Added run scripts

### PR DESCRIPTION
**Pull request by saturnism**

### CODE REVIEW

**Comment by saturnism** [comment]
However, the produced test service client doesn't run. fails with exception:
```
Exception in thread "main" kotlin.UninitializedPropertyAccessException: lateinit property testServiceExecutor has not been initialized
	at io.grpc.testing.integration.AbstractInteropTest.stopServer(AbstractInteropTest.kt:190)
	at io.grpc.testing.integration.AbstractInteropTest.tearDown(AbstractInteropTest.kt:262)
	at io.grpc.testing.integration.TestServiceClient.tearDown(TestServiceClient.kt:155)
	at io.grpc.testing.integration.TestServiceClient.access$tearDown(TestServiceClient.kt:46)
	at io.grpc.testing.integration.TestServiceClient$Companion.main(TestServiceClient.kt:318)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.kt)
```

the grpc-java test client assumes several defaults; the client and optional arguments should not be required.

**Comment by lowasser** [comment]
Working on this.  Merged some updates that should fix that issue when pulled, though I'm trying to figure out if there are other issues remaining.

**Comment by saturnism** [comment]
i did the pull, but now the code base failed to build.

```
.../grpc-kotlin/interop_testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.kt: (176, 27): Smart cast to 'ScheduledExecutorService!' is impossible, because 'testServiceExecutor' is a mutable property that could have been changed by this time
```

**Comment by lowasser** [comment]
Apologies, I thought I'd validated the build.  Fixed with #35 .

**Comment by saturnism** [comment]
Thanks. That worked :)

**Comment by saturnism** [comment]
@lowasser pushed the latest changes to grpc to run kotlin interop tests.  Docker image is now built successfully... However, upon execution:

```
START: interop_server_java

Unknown argument: server_port
Usage: [ARGS...]

 --server_host=HOST          Server to connect to. Default localhost
 --server_host_override=HOST Claimed identification expected of server.
                            Defaults to server host
 --server_port=PORT          Port to connect to. Default 8080
 --test_case=TESTCASE        Test case to run. Default empty_unary
   Valid options:
      empty_unary: empty (zero bytes) request and response
```

Trying to start the client locally w/ the argument also fails:

```
./run-test-client.sh --server_port=8081
Unknown argument: server_port
Usage: [ARGS...]
...
```

**Comment by lowasser** [comment]
I just pushed #36, which should help.

**Comment by saturnism** [comment]
awesome, i think this is good to go for now; the interop pr on grpc side will run the interop test. however, it's failing.

**Comment by saturnism** [comment]
https://github.com/grpc/grpc-kotlin/issues/37

**Comment by saturnism** [comment]
updated w/ the latest structure. prob good to go.

**Pull request merged**
